### ISSUE TITLE
LC missing data

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/diff-img#23]
Pipeline is rejecting too many points. I know these exposures exist and can create good photometry because I've done it in old versions of the code. The data around peak shouldn't be missing, here. 

![image](https://github.com/user-attachments/assets/f291b35f-1c8e-42e0-bf5c-647063b76f3b)

**Comment by laldoroty** [comment]
There are 38 files in the directory where the final difference images are saved. 12 of the images are entirely NaNs, and 2 are NaN at the SN but not entirely NaN. So, there should be 38-12-2 = 24. 

There are 23 points in the residual plot (I didn't fix the y limits for the residual). So, I'm not going to worry about the last one, because it might be doubled up. 

Here is an old version of the same plot. I'm counting 52 points in the residual plot. So, clearly there is an issue on the SFFT side of things. I should have at _least_ 52 output files. 
![image](https://github.com/user-attachments/assets/6cbf73bc-9601-4cb5-b171-fcb369e81e01)

**Comment by laldoroty** [comment]
There are 54 science images in the sky-subtracted directory. 
There are 53 unrotated science image PSFs in the PSF directory. 
There are 44 science images in the convolved directory. 
There are 44 difference images. 
There are 44 decorrelation kernels. 
There are 44 decorrelated science images for getting the zeropoint. 
There are 44 decorrelated difference images. 
There are 38 decorrelated difference image stamps. 
There are 38 decorrelated PSFs. 

I think the biggest loss here is when I cross-convolve the PSFs with the sky-subtracted images. Something funny is happening here to cause the image to be lost, for some reason. I wonder if this goes back to the same issue we were having with SWarp not saving the outputs? That would be weird, because the reference image gets aligned to the science image now, and the file gets overwritten for each image, so it should still be able to _find_ a file. 

The images that have stamps that are all NaNs are: `['/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_35088_2_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_50487_8_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_37396_8_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_41205_12_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_38155_11_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_35857_3_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_37391_6_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_36626_15_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_52020_1_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_44669_5_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_49333_1_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_44664_12_-_6_17.fits']`

**Comment by laldoroty** [comment]
/cwork/ is down, so what I was going to do:
- Run a subtraction in a Jupyter notebook step-by-step for an image that doesn't appear in the 'convolved' directory and see what happens.
- Check the SN RA, Dec in the original images for the ones that have stamps but the whole stamp is NaNs. These may be ok--the SN really may be outside the SCA.

**Comment by laldoroty** [comment]
R062_54300_16 is not in the convolved directory, but is in the skysub directory. It goes through the convolution step in the Jupyter notebook with no issue. 

In the output log from the last run, it quits for this image with `/work/lna18/imsub_out/align/align_skysub_Roman_TDS_simple_model_R062_6_17.fits does not sufficiently overlap with the SN. 
Images R062 54300 16 and R062 6 17 do not sufficiently overlap to do image subtraction.`

I am using the same reference image in the Jupyter notebook, and they definitely overlap enough to do image subtraction. Here's the reference image: 
![image](https://github.com/user-attachments/assets/5c5359f1-bc49-490f-b294-91cfc864eedb)

I wonder if I made an error in a try/except somewhere. It's weird to drop an image from sky subtraction to convolution and then say "they don't overlap enough to subtract".

**Comment by laldoroty** [comment]
Well, DCC just crashed, but here is the SN location on the science and reference images:
![image](https://github.com/user-attachments/assets/f436d807-9bf1-476d-b02b-c557a0eeb9fc)
![image](https://github.com/user-attachments/assets/ed365e21-c530-4e27-ae68-463760ed86ad)

What I was _going_ to do was draw a 1Kx1K box around the coordinate in the reference image. If that box contains any NaNs, that would be the reason it got rejected, and 1Kx1K is perhaps too large of a required overlap area. Eyeballing it, it doesn't look like that box should spill over the edge of the image, though.

**Comment by laldoroty** [comment]
Confirming the box size isn't the problem: 
![image](https://github.com/user-attachments/assets/c33c9cb3-9068-48c8-a2ca-999daa5238f3)

**Comment by laldoroty** [comment]
Here's check_overlap():
```
def check_overlap(ra,dec,temp_path,sci_path,data_ext=0,overlap_size=1000,verbose=False):
    """
    Does the science and template images sufficiently overlap, centered on
    the specified RA/Dec (SN location)?
    """
    with fits.open(temp_path) as hdu:
        temp_img = hdu[data_ext].data
        ra = hdu[0].header['CRVAL1']
        dec = hdu[0].header['CRVAL2']
        
    with fits.open(sci_path) as hdu:
        sci_wcs = WCS(hdu[0].header)
    try:
        coord = SkyCoord(ra=ra*u.deg,dec=dec*u.deg)
        ref_cutout = Cutout2D(temp_img,coord,overlap_size,wcs=sci_wcs,mode='partial')

        if verbose:
            print('The following images overlap sufficiently:')
            print(temp_path)
            print(sci_path)

        return True
```

If I show ref_cutout.data, the result is:
![image](https://github.com/user-attachments/assets/3a4d317f-0c64-44ea-a182-ad95ce366f93)

However, it returns True. Something is inconsistent. For this cutout, it should return False because there are NaNs in it (the blank spot).

**Comment by laldoroty** [comment]
Something is wrong with the WCS of the aligned image. I changed the function to:
```
# Testing check_overlap()...
def check_overlap(ra,dec,imgpath,data_ext=0,overlap_size=1000,verbose=False,show_cutout=False):
    """
    Does the science and template images sufficiently overlap, centered on
    the specified RA/Dec (SN location)?
    """
    
    # Open the template image because that's the one that's been rotated.
    with fits.open(imgpath) as hdu:
        img = hdu[data_ext].data
        ra = hdu[0].header['CRVAL1']
        dec = hdu[0].header['CRVAL2']
        wcs = WCS(hdu[data_ext].header)

    try:
        coord = SkyCoord(ra=ra*u.deg,dec=dec*u.deg)
        pxcoords = skycoord_to_pixel(coord,wcs)
        cutout = Cutout2D(img,pxcoords,overlap_size,mode='partial')

        print(np.unique(cutout.data))
        if show_cutout:
            z1,z2 = ZScaleInterval(n_samples=1000,
            contrast=0.25,
            max_reject=0.5,
            min_npixels=5,
            krej=2.5,
            max_iterations=5,
            ).get_limits(cutout.data)

            plt.figure()
            plt.imshow(cutout.data, vmin=z1, vmax=z2, cmap='Greys')

            plt.show()

        if verbose:
            print(f'The image {imgpath} contains sufficient overlap around coordinates {coord}.')

        return True

    except (PartialOverlapError, NoOverlapError):
        if verbose:
            print(f'{temp_path} does not sufficiently overlap with the SN. ')
        return False
    
check_overlap(ra,dec,ref_align_path,verbose=True,show_cutout=True)
```

I get the same output as above, which is wrong. 

But, if I put the pixel coordinates of the SN in directly from the original science image, this works correctly. I don't know that there's really anything to be done about astropy interpreting the WCS of the SWarp-aligned image strangely, but what I can do is just change the arguments of check_overlap from `ra,dec` to a pixel coordinate location.

**Comment by wmwv** [comment]
Sorry, I'm having a bit of trouble following the above discussion in terms of image cutouts.  Is there a simple: "compute two numbers two different ways" version of the test above?

**Comment by wmwv** [comment]
One specific question:
```
        ra = hdu[0].header['CRVAL1']
        dec = hdu[0].header['CRVAL2']
```
Why do you expect these to be the coordinates of the SN?

**Comment by laldoroty** [comment]
Fixed check_overlap() in sfft_and_animate.py, and also updated the corresponding unit test. Pushed, but I think DCC is still struggling with /cwork/, so the first two tests (that I didn't change) now won't run. So that's the caveat. Now checking the images with stamps that contain only NaNs. 

For `band, pointing, sca = 'R062', 35088, 2`, this image certainly does _not_ have an issue with the SN being located outside of the SCA: 
![image](https://github.com/user-attachments/assets/02ff5f51-82eb-4636-b805-f098f18d42e5)

And the rotated reference image is fine: 
![image](https://github.com/user-attachments/assets/932fbcce-bb9f-4ba8-94c5-26ba33f3a171)

So, betting this problem is related to the above problem.

**Comment by laldoroty** [comment]
> Sorry, I'm having a bit of trouble following the above discussion in terms of image cutouts. Is there a simple: "compute two numbers two different ways" version of the test above?

> One specific question:

>        ra = hdu[0].header['CRVAL1']
>        dec = hdu[0].header['CRVAL2']

> Why do you expect these to be the coordinates of the SN?

I think these questions are related--I had ['CRVAL'] in the test function, but I think some wires got crossed with what I was copying and pasting between my Jupyter notebook and my test function and the actual function. So, I don't expect that to be the coordinate of the SN. Here's what I have now: 

```
def check_overlap(x,y,imgpath,data_ext=0,overlap_size=1000,verbose=False,show_cutout=False):
    """
    Does the science and template images sufficiently overlap, centered on
    the specified x, y pixel coordinates (SN location)?
    """
    
    with fits.open(imgpath) as hdu:
        img = hdu[data_ext].data

    try:
        cutout = Cutout2D(img,(x,y),overlap_size,mode='strict')
        if show_cutout:
            z1,z2 = ZScaleInterval(n_samples=1000,
            contrast=0.25,
            max_reject=0.5,
            min_npixels=5,
            krej=2.5,
            max_iterations=5,
            ).get_limits(cutout.data)

            plt.figure()
            plt.imshow(cutout.data, vmin=z1, vmax=z2, cmap='Greys')

            plt.show()

        if verbose:
            print(f'The image {imgpath} contains sufficient overlap around pixel coordinates {x}, {y}.')

        return True

    except (PartialOverlapError, NoOverlapError):
        if verbose:
            print(f'{imgpath} does not sufficiently overlap with the SN. ')
        return False

```
def test_check_overlap():
    # Test that for a cutout around an image's center, it returns True.
    # For a cutout around a coordinate in the image, but the cutout spills over the edge, it returns False.
    # For a cutout around a coordinate not in the image, it returns False. 

    path = 'testdata/Roman_TDS_simple_model_R062_6_17.fits.gz'

    with fits.open(path) as hdu:
        x_in, y_in = hdu[0].header['CRPIX1'], hdu[0].header['CRPIX2']

    x_out, y_out = (4089, 4089)

    check1 = check_overlap(x_in,y_in,path,overlap_size=4088,data_ext=1)
    check2 = check_overlap(x_in,y_in,path,overlap_size=4089,data_ext=1)
    check3 = check_overlap(x_out,y_out,path,overlap_size=4088,data_ext=1)

    assert check1
    assert not check2
    assert not check3
```

```

**Comment by wmwv** [comment]
OK, but isn't the function you really want a `check_overlap(ra, dec, ...` version of this function.

If you really just want a `check_overlap(x, y, ...` you can just check x, y against NX, NY.

**Comment by laldoroty** [comment]
hmmm ok I think at some point some stuff from the test function got copied into check_overlap() because I changed it back and now it's fine. will have to be more careful in the future about this.

**Comment by laldoroty** [comment]
New SFFT running, set up mk_lc.py as a dependency after this finishes. It's running fine for now. Hooray! fingers crossed. Will probably take until tomorrow to see results.

**Comment by laldoroty** [comment]
Ooookay. Recovered a few more data points. I'm counting 27 points in the residual plot. 
![image](https://github.com/user-attachments/assets/57d3bbf3-5018-4c81-9f0c-406c16c76e42)

Now, I have:
54 unzipped original images
54 images in skysub
34 unrotated PSFs (?!)
34 convolved 
34 difference
34 decorrelation kernels

These numbers don't make any sense, but recording them for completeness. I thought I emptied the directories before I re-ran, but maybe I didn't do them all. If there are only 34 decorrelation kernels, there can't be more than 34 of any of these.
52 zero point images
52 decorrelated difference images
49 decorrelated PSFs
49 decorrelated difference image stamps

Will check an image in the Jupyter notebook that the output log says doesn't overlap enough to do image subtraction: R062 35857 3.

**Comment by laldoroty** [comment]
Ok, the overlap area does actually go over the edge for this one. There's a file for the stamp, but it's full of NaN.
![image](https://github.com/user-attachments/assets/2a1e4702-7365-4e1f-b70b-2e4d4c6e15a7)

I checked a few more, and they go over the edge, too.

R062 37391 6
![image](https://github.com/user-attachments/assets/1411ff2e-55df-4872-b8eb-819da20f6b4f)

R062 37395 16
![image](https://github.com/user-attachments/assets/3b02164c-58a4-4c9a-8e7b-a0e2028a8a32)

R062 37396 8
![image](https://github.com/user-attachments/assets/84601654-8ee2-4d72-8738-ee1612a01796)

So... I think I just need to decrease my overlap area. As far as I've tested, SFFT works best on a minimum stamp size of 1000x1000, but the last light curve looked pretty good, so I think I can decrease this. Plus, I'm not doing SFFT on stamps, I'm doing it on whole images, so there's area outside that box even if it spills over the edge (not sure if this matters). Also, there probably isn't any harm in running SFFT on a lot more stuff than is appropriate and rejecting bad photometry later. 

Maybe I decrease to like, 500x500.

**Comment by laldoroty** [comment]
Switched to 500x500 and re-ran. It takes like 6 hours to run, so if anyone has issues with this choice, let me know soon so I can stop it and restart. Will submit mk_lc.sh as a dependency so it automatically goes when SFFT is done.

**Comment by laldoroty** [comment]
After decreasing required overlap to 500x500:

54 sky-subtracted
46 PSFs
46 convolved 
46 difference
46 decorrelation kernels
46 decorrelated difference images
46 stamps of decorrelated difference images

Ctrl+F "do not sufficiently overlap" in the log file yields 7 results; 54-7 = 47

I think we can call this working appropriately, for now. I will try to hunt down that extra lost image later. There is still a discrepancy between the number of SFFT images and points in my LC plot, but now it's somehow missing a point from the previous one?! I am going to open every SFFT stamp and check that 21 of them aren't full of NaNs, and also check the values in the table from photometry. 
![image](https://github.com/user-attachments/assets/4e519ed1-164d-45fe-85ce-ef3a3e03cf53)

**Comment by laldoroty** [comment]
Most of the stamps are correct, and have the SN at the center, like this:
![image](https://github.com/user-attachments/assets/e607047d-5309-4601-a275-092dd506d6d2)

Two images look like this: 
![image](https://github.com/user-attachments/assets/ce33b591-6260-4d01-98e6-125e1c422fe8)

17 didn't want to plot, usually this is because they're all NaNs: `['/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_52395_18_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_53540_18_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_53160_15_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_35088_2_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_38920_3_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_50487_8_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_37396_8_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_41205_12_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_39680_15_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_40825_15_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_38155_11_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_35857_3_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_36626_15_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_52020_1_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_48174_11_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_44669_5_-_6_17.fits', '/work/lna18/imsub_out/decorr/stamps/dd_stamp_20172782_R062_49333_1_-_6_17.fits']`

Testing R062 39680 15 (from the above list) in the Jupyter notebook, it looks completely fine. Its output in the log file from last night also looks fine. 
![image](https://github.com/user-attachments/assets/8323e7b1-3223-47ef-92c7-38c5b9002a35)
![image](https://github.com/user-attachments/assets/ac86128c-1927-43b4-bf5c-3c8b9190e089)

However, its difference image looks crazy!
![image](https://github.com/user-attachments/assets/7131eae2-40e0-4568-88a6-aa4b438e9a07)

This one has SCA%3=0, and those SCAs are flipped, so I would not be surprised if there was a 180 deg alignment issue for these. But, if I check R062 35088 2, the issue is the same:
![image](https://github.com/user-attachments/assets/aeb8c845-4b42-4d25-9518-d066ba0229fa)

So... we are back to the alignment issue...

**Comment by laldoroty** [comment]
Also, why do the above images have identical shapes but different objects? That's odd?

**Comment by laldoroty** [comment]
It's true for R062_52020_1 as well. HMM. this is a hint for sure.
![image](https://github.com/user-attachments/assets/4cd87bca-67d0-4dbc-968b-2a905500d00b)

**Comment by laldoroty** [comment]
Wait. Wait wait wait. They are all like this. I plotted every difference image and they all look like this. Also, look at these stamps:
![image](https://github.com/user-attachments/assets/7d0fccef-09c5-4738-a690-88b0de7a1c10)
![image](https://github.com/user-attachments/assets/271ff37a-2e39-4141-a6fe-108c87b4500c)

If I do the first SN image in the sequence in the Jupyter notebook... the reference rotates like this. Problem solved. Accidentally using the same reference image for every exposure. Now just need to actually find it in the code. 

![image](https://github.com/user-attachments/assets/2702505c-7142-4de3-b0de-027572b52cc4)

**Comment by laldoroty** [comment]
Just had to set 'force=True' in imalign() :')

**Comment by laldoroty** [comment]
Much better (second image in sequence): 
![image](https://github.com/user-attachments/assets/821318cb-ab5e-4b6b-a14b-1e192c987a6b)

**Comment by laldoroty** [comment]
Functional. Closing this issue, opening PR. 
![image](https://github.com/user-attachments/assets/95e1e9cf-bafe-4e87-930d-4b1f0ac34a46)
