### ISSUE TITLE
Image overlap bug

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/diff-img#32]
Image pair R062 35083 8, R062 51222 2 caused preprocessing.py to crash with the following error:

```
Traceback (most recent call last):
  File "/global/cfs/cdirs/m4385/users/lauren/diff-img/preprocess.py", line 352, in <module>
    parse_and_run()
  File "/global/cfs/cdirs/m4385/users/lauren/diff-img/preprocess.py", line 348, in parse_and_run
    run(args.oid, args.band, args.sci_list_path, args.template_list_path, cpus_per_task=cpus_per_task, verbose=args.
verbose)
  File "/global/cfs/cdirs/m4385/users/lauren/diff-img/preprocess.py", line 239, in run
    preprocess(ra,dec,band,pair,verbose=verbose)
  File "/global/cfs/cdirs/m4385/users/lauren/diff-img/preprocess.py", line 170, in preprocess
    sci_conv, temp_conv = crossconvolve(sci_skysub_path,sci_psf_path,t_align,t_imsim_psf,sci_outname=sci_conv_name,ref_outname=ref_conv_name,force=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4385/users/lauren/phrosty/phrosty/imagesubtraction.py", line 335, in crossconvolve
    convolved = convolve_fft(imgdata, psfdata, boundary='fill', nan_treatment='fill', \
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/l/laldorot/.conda/envs/diff/lib/python3.11/site-packages/astropy/nddata/decorators.py", line 261, in wrapper
    result = func(data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/l/laldorot/.conda/envs/diff/lib/python3.11/site-packages/astropy/convolution/convolve.py", line 751, in convolve_fft
    raise Exception(
Exception: The kernel can't be normalized, because its sum is close to zero. The sum of the given kernel is < 0.01. For a zero-sum kernel, set normalize_kernel=False or pass a custom normalization function to normalize_kernel.
```

I opened each sky-subtracted image in DS9, along with the image where 51222 2 was aligned to 35083 8. It's blank. 
![image](https://github.com/user-attachments/assets/1cc627de-858a-4c8a-afc6-622646a84edb)

So, not only do the sky-subtracted images not overlap at all, but they're nowhere near each other. check_overlap() somehow didn't catch this.

**Comment by wmwv** [comment]
So is the bug that `check_overlap` didn't catch this?

**Comment by laldoroty** [comment]
It seems that 35083_8 doesn't contain the SN at all. These are the original images. The tiny green dots are the location of the SN. So... yes. But also, somehow, I grabbed a science image that doesn't contain the SN when I made my object list. 

The weirdest part is that I'm pretty sure I've been using 35083 8 as an example this entire time because I'm _pretty sure_ it's the first image that SN20172782 appears in for the R062 band. 

![image](https://github.com/user-attachments/assets/9933b67a-153b-4157-83ad-93fa6f412e38)

**Comment by laldoroty** [comment]
IT WAS A USER ERROR. MY BAD. IGNORE.

**Comment by laldoroty** [comment]
actually, maybe we shouldn't close this issue because check_overlap() still should have caught it.

**Comment by wmwv** [comment]
Agreed.  I think the bug is that `check_overlap` didn't catch this.  Can you produce a minimal example that verifies that passing the two images to `check_overlap` fails?

**Comment by laldoroty** [comment]
Yes--the issue appears to happen after alignment. 

```
imgpath_1 = '/global/cfs/cdirs/lsst/shared/external/roman-desc-sims/Roman_data/RomanTDS/images/simple_model/R062/51222/Roman_TDS_simple_model_R062_51222_2.fits.gz'
imgpath_2 = '/pscratch/sd/l/laldorot/A_vec/dia_out/align/align_skysub_Roman_TDS_simple_model_R062_51222_2_-_R062_35083_8.fits'

oid = 20172782
ra,dec = get_transient_radec(oid)

check_1 = check_overlap(ra,dec,imgpath_1,data_ext=1)
check_2 = check_overlap(ra,dec,imgpath_2,data_ext=0)

print(check_1, check_2)

>>> False True
```

**Comment by laldoroty** [comment]
I think check_overlap is working correctly, and the problem is in the implementation of it. Right now, I run:
```
template_overlap = check_overlap(ra,dec,t_align,verbose=verbose)
science_overlap = check_overlap(ra,dec,sci_skysub_path,verbose=verbose)
```

I should be checking the overlap on the sky-subtracted, un-aligned image in both cases. Not the aligned image.

**Comment by laldoroty** [comment]
I've fixed it in this commit: https://github.com/Roman-Supernova-PIT/diff-img/commit/448d84fc37b061952e5a5d90e04993ecec3bbef3

**Comment by laldoroty** [comment]
Actually, this is great because now I can even move the sky-subtraction step to after check_overlap, so now, if they don't overlap sufficiently (I can just check on the original images), we save time by not sky-subtracting at all.
